import {MD3LightTheme} from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#0ea5e9',
    primaryContainer: '#e0f2fe',
    secondary: '#64748b',
    secondaryContainer: '#f1f5f9',
    tertiary: '#d946ef',
    tertiaryContainer: '#fae8ff',
    surface: '#ffffff',
    surfaceVariant: '#f8fafc',
    background: '#ffffff',
    error: '#ef4444',
    errorContainer: '#fee2e2',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#0c4a6e',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#334155',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#701a75',
    onSurface: '#0f172a',
    onSurfaceVariant: '#475569',
    onBackground: '#0f172a',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    outline: '#cbd5e1',
    outlineVariant: '#e2e8f0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#1e293b',
    inverseOnSurface: '#f8fafc',
    inversePrimary: '#7dd3fc',
    elevation: {
      level0: 'transparent',
      level1: '#ffffff',
      level2: '#ffffff',
      level3: '#ffffff',
      level4: '#ffffff',
      level5: '#ffffff',
    },
  },
  roundness: 12,
}; 